CREATE TABLE shop_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    CONSTRAINT shop_user_pkey PRIMARY KEY (id)
);

CREATE TABLE category
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    allowed_attributes JSONB,
    name               VARCHAR(255),
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    attributes  JSONB,
    description VARCHAR(255),
    name        VARCHAR(255),
    price       NUMERIC(38, 2),
    category_id BIGINT,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE cart
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT cart_pkey PRIMARY KEY (id)
);

CREATE TABLE cart_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    cart_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT cart_item_pkey PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price      NUMERIC(38, 2)                          NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE order_item
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price_at_purchase NUMERIC(38, 2)                          NOT NULL,
    quantity          INTEGER                                 NOT NULL,
    order_id          BIGINT                                  NOT NULL,
    product_id        BIGINT                                  NOT NULL,
    CONSTRAINT order_item_pkey PRIMARY KEY (id)
);

ALTER TABLE cart ADD CONSTRAINT uk_cart_user_id UNIQUE (user_id);
ALTER TABLE shop_user ADD CONSTRAINT uk_shop_user_username UNIQUE (username);

ALTER TABLE product ADD CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE NO ACTION;
ALTER TABLE cart_item ADD CONSTRAINT fk_cart_item_cart FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE NO ACTION;
ALTER TABLE cart ADD CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES shop_user (id) ON DELETE NO ACTION;
ALTER TABLE cart_item ADD CONSTRAINT fk_cart_item_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE NO ACTION;

ALTER TABLE orders ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES shop_user (id) ON DELETE NO ACTION;
ALTER TABLE order_item ADD CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
ALTER TABLE order_item ADD CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE NO ACTION;